title: My Projects blog
description: My very nice blog
author: "Daniël Evers"

theme: minima

base_url: /
repository: holystaff/holystaff.github.io

# Minima social links
github_username: HolyStaff
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md
  - _pages/honoursportfolio.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
